Adiciona o fetch_agenda_camara
andresmrm/rcongresso pull request #17
Opened 2019-02-04 18:08 UTC by jairNeto

Conserta a issue #.

Mudanças propostas nesse PR:
-
-
-

@paul0vinicius

2019-02-07 13:28 UTC, JuanBarros2 requested changes

2019-02-07 13:28 UTC, JuanBarros2 commented on tests/testthat/test_agenda.R
> +  agenda <<- fetch_agenda_camara('2018-07-03', '2018-07-10')
Poderia criar um teste com uma semana específica e verificar se ele retorna a quantidade de linhas exatas visto que isso não mudaria com o tempo

2019-02-07 14:09 UTC, JuanBarros2 requested changes

2019-02-07 14:09 UTC, JuanBarros2 commented on R/agenda.R
> +.fetch_pauta_camara <- function(id, hora_inicio, hora_fim, sigla_orgao, nome_orgao) {
Poderia deixar pública

2019-02-07 14:22 UTC, JuanBarros2 commented on R/agenda.R
> +#' @param id id do evento
Necessita tradução

2019-02-07 14:24 UTC, JuanBarros2 commented on R/agenda.R
> +#' @param end_date dend date formato yyyy-mm-dd
.

2019-02-11 12:14 UTC, danielrcoura commented on R/constants.R
> +.AGENDA_CAMARA_PATH <- "/api/v2/eventos?dataInicio="
É bom separar o path da query. Ficaria apenas: /api/v2/eventos

2019-02-12 17:18 UTC, danielrcoura commented on R/agenda.R
> +  json_proposicao <- .camara_api(url)
pode separar a query do path da url em .camara_api
```.camara_api <- function(path=NULL, query=NULL, asList = FALSE){```

2019-02-13 13:21 UTC, JuanBarros2 approved these changes

2019-02-13 13:22 UTC, merged