767 fetch apensados
andresmrm/rcongresso pull request #19
Opened 2019-02-05 11:59 UTC by danielrcoura

2019-02-06 16:02 UTC, jairNeto commented
> # [Codecov](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=h1) Report
> > Merging [#19](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=desc) into [master](https://codecov.io/gh/andresmrm/rcongresso/commit/6d6f6256f95cd97fc4ddd189108af9a0baa6e433?src=pr&el=desc) will **decrease** coverage by `2.08%`.
> > The diff coverage is `100%`.
> 
> [![Impacted file tree graph](https://camo.githubusercontent.com/12a3d0e0f82950445c98faab0fc63b1e434706d2/68747470733a2f2f636f6465636f762e696f2f67682f616e647265736d726d2f72636f6e67726573736f2f70756c6c2f31392f6772617068732f747265652e7376673f77696474683d36353026746f6b656e3d4e467448575533644862266865696768743d313530267372633d7072)](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=tree)
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master      #19      +/-   ##
> ==========================================
> - Coverage   90.35%   88.27%   -2.09%     
> ==========================================
>   Files           8        8              
>   Lines         446      452       +6     
> ==========================================
> - Hits          403      399       -4     
> - Misses         43       53      +10
> ```
> 
> [Impacted Files](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=tree)	Coverage Δ	
> [R/proposicoes.R](https://codecov.io/gh/andresmrm/rcongresso/pull/19/diff?src=pr&el=tree#diff-Ui9wcm9wb3NpY29lcy5S)	`100% <100%> (ø)`	
> [R/utils.R](https://codecov.io/gh/andresmrm/rcongresso/pull/19/diff?src=pr&el=tree#diff-Ui91dGlscy5S)	`75.64% <0%> (-5.19%)`	
> [Continue to review full report at Codecov](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=footer). Last update [6d6f625...2925ceb](https://codecov.io/gh/andresmrm/rcongresso/pull/19?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

Tem que melhorar a cobertura dos testes

2019-02-07 11:29 UTC, danielrcoura commented
A cobertura diminuiu por causa do utils.R, que a gente não está testando.

2019-02-08 14:32 UTC, JuanBarros2 requested changes

2019-02-08 14:32 UTC, JuanBarros2 commented on tests/testthat/test_apensadas.R
> +
Seria bom testar com uma PL que já terminou e verificar se o número de apensadas bate com o valor real

2019-02-11 12:06 UTC, danielrcoura commented on tests/testthat/test_apensadas.R
> +
Aparentemente quando um PL é aprovado, suas apensadas não são mais exibidas no site da Câmara. Fiz uma pesquisa mais avançada no google e estes são os PLs aprovados, mas nenhum deles possui apensadas: https://www.google.com/search?as_q=pl+lei+ordin%C3%A1ria&as_epq=Situa%C3%A7%C3%A3o%3A+Transformado+na+Lei+Ordin%C3%A1ria&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=www.camara.leg.br&as_occt=any&safe=images&as_filetype=&as_rights=

2019-02-11 12:07 UTC, danielrcoura commented on tests/testthat/test_apensadas.R
> +
As apensadas ficam em "Árvore de apensados e outros documentos da matéria"

2019-02-11 14:26 UTC, JuanBarros2 commented on tests/testthat/test_apensadas.R
> +
Vê se aparece nessa aqui https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1214970

2019-02-12 18:11 UTC, danielrcoura commented on tests/testthat/test_apensadas.R
> +
Não apareceu

2019-02-14 12:53 UTC, JuanBarros2 requested changes

2019-02-14 12:53 UTC, JuanBarros2 commented on R/proposicoes.R
> +#' @title Fetch the appended propositions
É bom deixar claro na documentação que essas apensadas só são da câmara

2019-02-15 12:55 UTC, closed without merging