Adiciona fetch_agenda_comissoes
andresmrm/rcongresso pull request #26
Opened 2019-02-08 19:27 UTC by jairNeto

Conserta a issue #.

Mudanças propostas nesse PR:
-
-
-

@paul0vinicius

2019-02-12 18:09 UTC, danielrcoura requested changes

2019-02-12 18:09 UTC, danielrcoura commented on R/agenda.R
> +.pega_nome <- function(l){
O nome da função não está descritivo, poderia ser algo como .get_proposicoes_from_agenda. O parâmetro "l" também não está.

2019-02-12 18:09 UTC, danielrcoura commented on R/agenda.R
> +  if(length(l$Tipo) == 1) {
Poderia ter uma variável com o que deve ser retornado para evitar os "else" e deixar o código mais limpo.
``` 
nome <- ""
if(length(l$Tipo) == 1) {
    if (l$Tipo == "Deliberativa") {
      nome <- paste(l$Itens$Item$Nome, collapse = ",")
    }
} else {
  if ("Deliberativa" %in% l$Tipo) {
    if(!is.null(l$Itens.Item)) {
      nome <- paste(l$Nome, collapse = ",")
    }
}  
nome
```

2019-02-12 18:09 UTC, danielrcoura commented on R/agenda.R
> +  if(length(l$Tipo) == 1 ) {
Mesma coisa do comentários acima.

2019-02-12 18:09 UTC, danielrcoura commented on R/agenda.R
> +.pega_id_proposicao <- function(l){
Nome da função e do parâmetro mais descritivos.

2019-02-13 12:31 UTC, jairNeto commented on R/agenda.R
> +.pega_nome <- function(l){
Como se pode ver pelo ponto na frente da função e a ausência do @export esta função é privada, apenas utilizada uma vez dentro de um map, logo não há a necessidade de um nome super expressivo, com respeito ao parâmetro l, l indica lista igual df que é usado constatemente no código para indicar dataframe

2019-02-13 12:46 UTC, JuanBarros2 commented on R/agenda.R
> +.pega_nome <- function(l){
Concordo com @danielrcoura. Melhor padronizar o nome das funções mesmo as privadas, pois a legibilidade deve ser mantida para todo o código

2019-02-14 11:23 UTC, JuanBarros2 requested changes

2019-02-14 11:23 UTC, JuanBarros2 commented on R/agenda.R
> +.pega_id_proposicao_agenda_senado_comissoes <- function(lista_com_id){
Acredito que "get" se encaixa melhor no padrão do RCongresso

2019-02-14 11:23 UTC, JuanBarros2 commented on R/agenda.R
> +.pega_nome_proposicao_agenda_senado_comissoes <- function(lista_com_nome){
"Get"

2019-02-14 12:38 UTC, danielrcoura approved these changes

2019-02-14 12:47 UTC, JuanBarros2 approved these changes

2019-02-14 12:47 UTC, merged