fetch orgaos camara
andresmrm/rcongresso pull request #6
Opened 2019-01-25 12:59 UTC by andresmrm

2019-01-29 12:01 UTC, thayannevls requested changes

2019-01-29 12:01 UTC, thayannevls commented on R/orgaos.R
> +    tibble::as.tibble() %>%
Aqui era bom seguir o padrão das outras funções não? Usando as funções `.assert_dataframe_completo` e o `.coerce_types`

2019-01-29 12:01 UTC, thayannevls commented on R/orgaos.R
> +    tibble::as.tibble() %>%
Também em colocar os nomes das colunas

2019-01-30 12:19 UTC, thayannevls approved these changes

2019-02-05 20:13 UTC, jairNeto approved these changes

2019-02-05 20:13 UTC, merged